name: Software Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: check out git repository
        uses: actions/checkout@v2

      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        with:
          tagRegex: "v(.*)"

      - name: setup node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: software

      - name: build application
        run: yarn build
        working-directory: software
        env:
          KERMITE_APP_VERSION: ${{ steps.tagName.outputs.tag }}

      - name: build distribution package (mac)
        if: matrix.os == 'macos-latest'
        run: yarn packaging:mac
        working-directory: software

      - name: build distribution package (win)
        if: matrix.os == 'windows-latest'
        run: yarn packaging:win
        working-directory: software

      - name: make release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            software/release/*.pkg
            software/release/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
